/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdRevenue { 'impressions' : bigint, 'totalRevenue' : number }
export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface ExtendedVideo {
  'title' : string,
  'likeCount' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'file' : ExternalBlob,
  'tags' : Array<string>,
  'description' : string,
  'viewCount' : bigint,
  'commentCount' : bigint,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export type ExternalBlob = Uint8Array;
export interface RazorpayConfig { 'keyId' : string, 'keySecret' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'channelName' : [] | [string],
  'name' : string,
  'accountCreation' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalVideosUploaded' : bigint,
  'accountCreation' : Time,
  'totalPhotosUploaded' : bigint,
}
export interface VideoMetadata {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'thumbnail' : [] | [ExternalBlob],
  'tags' : Array<string>,
  'description' : string,
  'viewCount' : bigint,
  'commentCount' : bigint,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getAdRevenueForCaller' : ActorMethod<[], number>,
  'getAdRevenueForVideo' : ActorMethod<[string], AdRevenue>,
  'getAdSensePublisherId' : ActorMethod<[], [] | [string]>,
  'getAverageRating' : ActorMethod<[string], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelName' : ActorMethod<[Principal], [] | [string]>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getRazorpayConfig' : ActorMethod<[], [] | [RazorpayConfig]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalRatings' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRatings' : ActorMethod<
    [],
    Array<{ 'rating' : bigint, 'videoId' : string }>
  >,
  'getUserStats' : ActorMethod<[Principal], [] | [UserStats]>,
  'getVideo' : ActorMethod<[string], [] | [ExtendedVideo]>,
  'incrementVideoView' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRazorpayConfiguredLegacy' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'listVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'markThumbnailGenerated' : ActorMethod<[string, ExternalBlob], undefined>,
  'rateVideo' : ActorMethod<[string, bigint], undefined>,
  'recordAdImpression' : ActorMethod<[string], undefined>,
  'removeVideoThumbnail' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdSensePublisherId' : ActorMethod<[string], undefined>,
  'setChannelName' : ActorMethod<[string], undefined>,
  'setCustomThumbnail' : ActorMethod<[string, ExternalBlob], undefined>,
  'setRazorpayConfiguration' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVideo' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'uploadVideo' : ActorMethod<
    [string, string, Array<string>, ExternalBlob],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];