/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Photo {
  'title' : string,
  'file' : Uint8Array,
  'description' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface PhotoMetadata {
  'id' : string,
  'title' : string,
  'description' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'channelName' : [] | [string],
  'name' : string,
  'accountCreation' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalVideosUploaded' : bigint,
  'accountCreation' : Time,
  'totalPhotosUploaded' : bigint,
}
export interface Video {
  'title' : string,
  'likeCount' : bigint,
  'file' : Uint8Array,
  'description' : string,
  'commentCount' : bigint,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface VideoMetadata {
  'id' : string,
  'title' : string,
  'likeCount' : bigint,
  'description' : string,
  'commentCount' : bigint,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<
    [string, string],
    {
      'id' : bigint,
      'content' : string,
      'author' : Principal,
      'timestamp' : Time,
    }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteComment' : ActorMethod<[string, bigint], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelName' : ActorMethod<[Principal], string>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getPhoto' : ActorMethod<[string], Photo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[Principal], UserStats>,
  'getVideo' : ActorMethod<[string], Video>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'listPhotos' : ActorMethod<[], Array<PhotoMetadata>>,
  'listVideos' : ActorMethod<[], Array<VideoMetadata>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoMetadata>>,
  'setChannelName' : ActorMethod<[string], undefined>,
  'updateComment' : ActorMethod<[string, bigint, string], undefined>,
  'updatePhoto' : ActorMethod<[string, string, string], undefined>,
  'updateVideo' : ActorMethod<[string, string, string], undefined>,
  'uploadPhoto' : ActorMethod<[string, string, Uint8Array], string>,
  'uploadVideo' : ActorMethod<[string, string, Uint8Array], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];