/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'channelName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Photo = IDL.Record({
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const Video = IDL.Record({
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const PhotoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'description' : IDL.Text,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Nat,
          'content' : IDL.Text,
          'author' : IDL.Principal,
          'timestamp' : Time,
        }),
      ],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'listPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'setChannelName' : IDL.Func([IDL.Text], [], []),
  'updateComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updatePhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Text], []),
  'uploadVideo' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'channelName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Photo = IDL.Record({
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const Video = IDL.Record({
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const PhotoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'description' : IDL.Text,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Nat,
            'content' : IDL.Text,
            'author' : IDL.Principal,
            'timestamp' : Time,
          }),
        ],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [Video], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'listPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
    'setChannelName' : IDL.Func([IDL.Text], [], []),
    'updateComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updatePhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };