/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdRevenue = IDL.Record({
  'impressions' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'channelName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'accountCreation' : Time,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const RazorpayConfig = IDL.Record({
  'keyId' : IDL.Text,
  'keySecret' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserStats = IDL.Record({
  'totalVideosUploaded' : IDL.Nat,
  'accountCreation' : Time,
  'totalPhotosUploaded' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExtendedVideo = IDL.Record({
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAdRevenueForCaller' : IDL.Func([], [IDL.Float64], ['query']),
  'getAdRevenueForVideo' : IDL.Func([IDL.Text], [AdRevenue], ['query']),
  'getAdSensePublisherId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalRatings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'rating' : IDL.Nat, 'videoId' : IDL.Text }))],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(UserStats)], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(ExtendedVideo)], ['query']),
  'incrementVideoView' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfiguredLegacy' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'markThumbnailGenerated' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'rateVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'recordAdImpression' : IDL.Func([IDL.Text], [], []),
  'removeVideoThumbnail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdSensePublisherId' : IDL.Func([IDL.Text], [], []),
  'setChannelName' : IDL.Func([IDL.Text], [], []),
  'setCustomThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'setRazorpayConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdRevenue = IDL.Record({
    'impressions' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'channelName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'accountCreation' : Time,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const RazorpayConfig = IDL.Record({
    'keyId' : IDL.Text,
    'keySecret' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserStats = IDL.Record({
    'totalVideosUploaded' : IDL.Nat,
    'accountCreation' : Time,
    'totalPhotosUploaded' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExtendedVideo = IDL.Record({
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAdRevenueForCaller' : IDL.Func([], [IDL.Float64], ['query']),
    'getAdRevenueForVideo' : IDL.Func([IDL.Text], [AdRevenue], ['query']),
    'getAdSensePublisherId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalRatings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'rating' : IDL.Nat, 'videoId' : IDL.Text }))],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [IDL.Opt(UserStats)], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(ExtendedVideo)], ['query']),
    'incrementVideoView' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfiguredLegacy' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'markThumbnailGenerated' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'rateVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'recordAdImpression' : IDL.Func([IDL.Text], [], []),
    'removeVideoThumbnail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdSensePublisherId' : IDL.Func([IDL.Text], [], []),
    'setChannelName' : IDL.Func([IDL.Text], [], []),
    'setCustomThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'setRazorpayConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };