/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rating = IDL.Record({
  'value' : IDL.Nat,
  'timestamp' : Time,
  'reviewer' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'channelName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'accountCreation' : Time,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Photo = IDL.Record({
  'title' : IDL.Text,
  'file' : IDL.Vec(IDL.Nat8),
  'description' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const UserStats = IDL.Record({
  'totalVideosUploaded' : IDL.Nat,
  'accountCreation' : Time,
  'totalPhotosUploaded' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ExtendedVideo = IDL.Record({
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const VideoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'viewCount' : IDL.Nat,
  'commentCount' : IDL.Nat,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const PhotoMetadata = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Nat,
          'content' : IDL.Text,
          'author' : IDL.Principal,
          'timestamp' : Time,
        }),
      ],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getAllVideoRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
  'getRatingAnalytics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalRatings' : IDL.Nat,
          'ratingBreakdown' : IDL.Vec(IDL.Nat),
          'averageRating' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getTotalRatings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRatings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Rating))],
      ['query'],
    ),
  'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
  'getVideo' : IDL.Func([IDL.Text], [ExtendedVideo], ['query']),
  'getVideoMetadata' : IDL.Func([IDL.Text], [VideoMetadata], ['query']),
  'incrementVideoView' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'listPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
  'markThumbnailGenerated' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'rateVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeThumbnail' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
  'setChannelName' : IDL.Func([IDL.Text], [], []),
  'setCustomThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'updateComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updatePhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'uploadPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rating = IDL.Record({
    'value' : IDL.Nat,
    'timestamp' : Time,
    'reviewer' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'channelName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'accountCreation' : Time,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Photo = IDL.Record({
    'title' : IDL.Text,
    'file' : IDL.Vec(IDL.Nat8),
    'description' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const UserStats = IDL.Record({
    'totalVideosUploaded' : IDL.Nat,
    'accountCreation' : Time,
    'totalPhotosUploaded' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ExtendedVideo = IDL.Record({
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const VideoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'viewCount' : IDL.Nat,
    'commentCount' : IDL.Nat,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const PhotoMetadata = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Nat,
            'content' : IDL.Text,
            'author' : IDL.Principal,
            'timestamp' : Time,
          }),
        ],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getAllVideoRatings' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
    'getRatingAnalytics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalRatings' : IDL.Nat,
            'ratingBreakdown' : IDL.Vec(IDL.Nat),
            'averageRating' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTotalRatings' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRatings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Rating))],
        ['query'],
      ),
    'getUserStats' : IDL.Func([IDL.Principal], [UserStats], ['query']),
    'getVideo' : IDL.Func([IDL.Text], [ExtendedVideo], ['query']),
    'getVideoMetadata' : IDL.Func([IDL.Text], [VideoMetadata], ['query']),
    'incrementVideoView' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'listPhotos' : IDL.Func([], [IDL.Vec(PhotoMetadata)], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(VideoMetadata)], ['query']),
    'markThumbnailGenerated' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'rateVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeThumbnail' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoMetadata)], ['query']),
    'setChannelName' : IDL.Func([IDL.Text], [], []),
    'setCustomThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'updateComment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updatePhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'uploadPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };